### ISSUE TITLE
Profile switching from menu changes Recording but not Playback

### ISSUE THREAD

**Issue by conan** [Belphemur/SoundSwitch#1126]
### What happened?

I've set up two profiles with each switching both output and recording at the same time.  One selects my speaker and mic, the other my headset and the headset mic.  Both profiles change both Default and Default Communications device. Hotkeys are disabled. Each profile only has a menu trigger, and is set to change Default device.

Switching profiles using the menu changes the Recording device but not the Playback device.  Soundswitch displays that both devices have changed, when in fact only the Recording device has.  This happens whichever devices are selected in the Sound control panel: Soundswitch is always unable to change Playback device.

I've tried reinstalling soundswitch and re-creating the profiles.  Any help welcome!

![image](https://user-images.githubusercontent.com/3037019/219945198-de122973-0ec4-4a83-b076-8f291ec22ea4.png)
![image](https://user-images.githubusercontent.com/3037019/219945205-d1ebe533-d705-492a-a46b-594602d53ab7.png)
![image](https://user-images.githubusercontent.com/3037019/219945995-6806d91a-234d-4039-9527-bab8da1b58c7.png)
![image](https://user-images.githubusercontent.com/3037019/219945275-45a9365a-1221-4535-898b-36e5084d19c3.png)
![image](https://user-images.githubusercontent.com/3037019/219945294-31ed76db-87f5-47e6-b28c-d199fff3a012.png)
![image](https://user-images.githubusercontent.com/3037019/219945503-d08ec490-084d-4303-9698-c340baf72b4a.png)

![k8EGroSZOi](https://user-images.githubusercontent.com/3037019/219946282-68e9833c-9aa7-4b9b-b542-d0cc4007cda5.gif)

### Step to reproduce

1. Create profile setting headset for Default and Default Communications devices for Playback and Rrecording, with menu trigger
2. Create profile setting speaker and mic and for Default and Default Communications device for Playback and Recording, with menu trigger
3. Use soundswitch menu to select a profile that changes devices.  
4. Compare Soundswitch menu to Sound control panel.  Recording devices match but Playback devices do not.

### Version

6.5.4.0

### What version of Windows are you seeing the problem on?

Windows 11

**Comment by conan** [comment]
This is still happening.  I've tried reinstalling the yeti mic.  It's only one way that it won't switch - switching back to headset works fine, but switching to yeti never works from a profile.

**Comment by Belphemur** [comment]
Should be fixed in the latest Nightly, can you give it a try ?
https://soundswitch.aaflalo.me/nightly

**Comment by conan** [comment]
Hi, unfortunately the problem still persists using SoundSwitch Nightly 6.5.3.2096
